@Api_HostAddress = https://localhost:7114

### Get all products (will be cached for 30 seconds with tags "products", "all")
GET {{Api_HostAddress}}/api/products
Accept: application/json
###

GET {{Api_HostAddress}}/api/products/1
Accept: application/json
